# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Labdoc < Formula
  desc "Automatically generate documentation for GitLab CI/CD components and CI/CD pipelines."
  homepage "https://github.com/erNail/labdoc"
  version "2.0.2-rc"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/erNail/labdoc/releases/download/2.0.2-rc/labdoc_2.0.2-rc_darwin_amd64.tar.gz"
      sha256 "9da803e9b66d304824d72dcc2e34272ba590eaa428fcdd5688136a3667a142e0"

      def install
        bin.install "labdoc"
      end
    end
    on_arm do
      url "https://github.com/erNail/labdoc/releases/download/2.0.2-rc/labdoc_2.0.2-rc_darwin_arm64.tar.gz"
      sha256 "cc1a9bc4b7105cf593ccb8f8c0f61ce53b4cd223286c00af15236740464e1851"

      def install
        bin.install "labdoc"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/erNail/labdoc/releases/download/2.0.2-rc/labdoc_2.0.2-rc_linux_amd64.tar.gz"
        sha256 "b65cf903e7c28a2f7cd540834be146c056eac8f21c87c201b252b0dc7edf555e"

        def install
          bin.install "labdoc"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/erNail/labdoc/releases/download/2.0.2-rc/labdoc_2.0.2-rc_linux_arm64.tar.gz"
        sha256 "976334b39698e200c82deec808f86f628686b4e2487f477a3c2290424d5140b1"

        def install
          bin.install "labdoc"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Run `labdoc -h` to get started!
    EOS
  end
end
