# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Verscout < Formula
  desc "Find the latest version tag, calculate the next version, print to STDOUT - no tagging, no bumping, no changelog, no publishing.
"
  homepage "https://github.com/erNail/verscout"
  version "1.5.0-rc14693029519"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/erNail/verscout/releases/download/1.5.0-rc14693029519/verscout_1.5.0-rc14693029519_darwin_amd64.tar.gz"
      sha256 "1b724ccea220a65ed14a83f69ea1cb1907be49d6f1b61851c5a77477ed1827fd"

      def install
        bin.install "verscout"
      end
    end
    on_arm do
      url "https://github.com/erNail/verscout/releases/download/1.5.0-rc14693029519/verscout_1.5.0-rc14693029519_darwin_arm64.tar.gz"
      sha256 "099188260dff739d4297e9b5689f50ee7474cdc30dde3723938aad61eb21ad51"

      def install
        bin.install "verscout"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/erNail/verscout/releases/download/1.5.0-rc14693029519/verscout_1.5.0-rc14693029519_linux_amd64.tar.gz"
        sha256 "139cee28e2f91a8c9a368c8082b458c6aa2bd668d75f61700464f82b0b66be30"

        def install
          bin.install "verscout"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/erNail/verscout/releases/download/1.5.0-rc14693029519/verscout_1.5.0-rc14693029519_linux_arm64.tar.gz"
        sha256 "07fbdbc0d2fc6af4b84e712fa6e1332672454184f85d3f20e0a8880afc438d84"

        def install
          bin.install "verscout"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Run `verscout -h` to get started!
    EOS
  end
end
