# This file was generated by GoReleaser. DO NOT EDIT.
cask "labdoc" do
  version "3.0.0"

  on_macos do
    on_intel do
      sha256 "7d32cfbb71a9c8782ee90aaef2515b4dcd8d94da2a1fbb93dc00c88fde7a0ad7"
      url "https://github.com/erNail/labdoc/releases/download/#{version}/labdoc_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9661e34366db585161ec424d2e964cd73483600296451cd64464210d08f16dbe"
      url "https://github.com/erNail/labdoc/releases/download/#{version}/labdoc_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "785b300a569a29cda7e163b08f2130e696ced9cf4be4816afb6804426bd533e6"
      url "https://github.com/erNail/labdoc/releases/download/#{version}/labdoc_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cf394538516892fd97ff1239cca21507a60f3e6121e5ecdb81c3fd8d381a47bc"
      url "https://github.com/erNail/labdoc/releases/download/#{version}/labdoc_#{version}_linux_arm64.tar.gz"
    end
  end

  name "labdoc"
  desc "Automatically generate documentation for GitLab CI/CD components and CI/CD pipelines."
  homepage "https://github.com/erNail/labdoc"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "labdoc"

  # No zap stanza required

  caveats <<~EOS
    Run `labdoc -h` to get started!
  EOS
end
